/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardgame;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author system1
 */
public class GameofCards extends javax.swing.JFrame {
 public static final int NCARDS = 52;
   Cards card[]=new Cards[NCARDS];
  int  currentCard=0;
  JLabel Front[]=new JLabel[NCARDS];
  Cards One,Two;
    /**
     * Creates new form GameofCards
     */
    public GameofCards() {
        initComponents();
         this.getContentPane().setBackground(Color.PINK);
     
       
          Front[0]=lb_1;     
          Front[1]=lb_2;  
          Front[2]=lb_3;  
          Front[3]=lb_4;  
          Front[4]=lb_5;  
          Front[5]=lb_6;  
          Front[6]=lb_7;  
          Front[7]=lb_8;  
          Front[8]=lb_9;  
          Front[9]=lb_10;  
          Front[10]=lb_11;  
          Front[11]=lb_12;  
           Front[12]=lb_13;  
          Front[13]=lb_14;  
           Front[14]=lb_15;  
          Front[15]=lb_16;  
           Front[16]=lb_17;  
          Front[17]=lb_18;  
           Front[18]=lb_19;  
          Front[19]=lb_20;  
           Front[20]=lb_21;  
          Front[21]=lb_22;  
          
            Front[22]=lb_23;     
          Front[23]=lb_24;  
          Front[24]=lb_25;  
           
          Front[25]=lb_26;  
          Front[26]=lb_27;  
          Front[27]=lb_28;  
          Front[28]=lb_29;  
          Front[29]=lb_30;  
          Front[30]=lb_31;  
          Front[31]=lb_32;  
           Front[32]=lb_33;  
          Front[33]=lb_34;  
           Front[34]=lb_35;  
          Front[35]=lb_36;  
           Front[36]=lb_37;  
          Front[37]=lb_38;  
           Front[38]=lb_39;  
          Front[39]=lb_40;  
           Front[40]=lb_41;  
         
            Front[41]=lb_42;  
          Front[42]=lb_43;  
           Front[43]=lb_44;  
          Front[44]=lb_45;  
                    
          Front[45]=lb_46;  
          Front[46]=lb_47;  
          Front[47]=lb_48;  
          Front[48]=lb_49;  
          Front[49]=lb_50;  
          Front[50]=lb_51;  
         Front[51]=lb_52;  
      
        
    }
    
   public void generate(){
       int i = 0;
    
     for(suit s:suit.values()){
       for( rank r:rank.values()){
           
           card[i]=new Cards(r,s);
           Front[i].setIcon(card[i].img);
           i++;
           }
           
       }
      }
    public void Shuffle(int n){
 
 
    for (int i = 0; i < n; i++) {
            int r = (int) (Math.random() * (NCARDS));
               int s = (int) (Math.random() * (NCARDS));
            Cards t = card[r];
            card[r] = card[s];
            card[s] = t;
        }
       
    }

 
 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_1 = new javax.swing.JLabel();
        lb_14 = new javax.swing.JLabel();
        lb_2 = new javax.swing.JLabel();
        lb_15 = new javax.swing.JLabel();
        lb_3 = new javax.swing.JLabel();
        lb_16 = new javax.swing.JLabel();
        lb_4 = new javax.swing.JLabel();
        lb_17 = new javax.swing.JLabel();
        lb_5 = new javax.swing.JLabel();
        lb_18 = new javax.swing.JLabel();
        lb_19 = new javax.swing.JLabel();
        lb_6 = new javax.swing.JLabel();
        lb_7 = new javax.swing.JLabel();
        lb_20 = new javax.swing.JLabel();
        lb_21 = new javax.swing.JLabel();
        lb_8 = new javax.swing.JLabel();
        lb_9 = new javax.swing.JLabel();
        lb_22 = new javax.swing.JLabel();
        lb_23 = new javax.swing.JLabel();
        lb_10 = new javax.swing.JLabel();
        lb_11 = new javax.swing.JLabel();
        lb_24 = new javax.swing.JLabel();
        lb_25 = new javax.swing.JLabel();
        lb_12 = new javax.swing.JLabel();
        lb_26 = new javax.swing.JLabel();
        lb_13 = new javax.swing.JLabel();
        lb_39 = new javax.swing.JLabel();
        lb_38 = new javax.swing.JLabel();
        lb_37 = new javax.swing.JLabel();
        lb_36 = new javax.swing.JLabel();
        lb_35 = new javax.swing.JLabel();
        lb_34 = new javax.swing.JLabel();
        lb_33 = new javax.swing.JLabel();
        lb_46 = new javax.swing.JLabel();
        lb_47 = new javax.swing.JLabel();
        lb_48 = new javax.swing.JLabel();
        lb_49 = new javax.swing.JLabel();
        lb_50 = new javax.swing.JLabel();
        lb_51 = new javax.swing.JLabel();
        lb_52 = new javax.swing.JLabel();
        lb_45 = new javax.swing.JLabel();
        lb_32 = new javax.swing.JLabel();
        lb_31 = new javax.swing.JLabel();
        lb_44 = new javax.swing.JLabel();
        lb_43 = new javax.swing.JLabel();
        lb_30 = new javax.swing.JLabel();
        lb_29 = new javax.swing.JLabel();
        lb_42 = new javax.swing.JLabel();
        lb_41 = new javax.swing.JLabel();
        lb_28 = new javax.swing.JLabel();
        lb_27 = new javax.swing.JLabel();
        lb_40 = new javax.swing.JLabel();
        btn_gen = new javax.swing.JButton();
        Shuffle = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_second = new javax.swing.JButton();
        btn_com = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Card Shuffling Game", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        lb_1.setBackground(new java.awt.Color(0, 204, 255));
        lb_1.setForeground(new java.awt.Color(0, 0, 204));
        lb_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_14.setBackground(new java.awt.Color(0, 204, 255));
        lb_14.setForeground(new java.awt.Color(0, 0, 204));
        lb_14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_2.setBackground(new java.awt.Color(0, 204, 255));
        lb_2.setForeground(new java.awt.Color(0, 0, 204));
        lb_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_15.setBackground(new java.awt.Color(0, 204, 255));
        lb_15.setForeground(new java.awt.Color(0, 0, 204));
        lb_15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_3.setBackground(new java.awt.Color(0, 204, 255));
        lb_3.setForeground(new java.awt.Color(0, 0, 204));
        lb_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_16.setBackground(new java.awt.Color(0, 204, 255));
        lb_16.setForeground(new java.awt.Color(0, 0, 204));
        lb_16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_4.setBackground(new java.awt.Color(0, 204, 255));
        lb_4.setForeground(new java.awt.Color(0, 0, 204));
        lb_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_17.setBackground(new java.awt.Color(0, 204, 255));
        lb_17.setForeground(new java.awt.Color(0, 0, 204));
        lb_17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_5.setBackground(new java.awt.Color(0, 204, 255));
        lb_5.setForeground(new java.awt.Color(0, 0, 204));
        lb_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_18.setBackground(new java.awt.Color(0, 204, 255));
        lb_18.setForeground(new java.awt.Color(0, 0, 204));
        lb_18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_19.setBackground(new java.awt.Color(0, 204, 255));
        lb_19.setForeground(new java.awt.Color(0, 0, 204));
        lb_19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_6.setBackground(new java.awt.Color(0, 204, 255));
        lb_6.setForeground(new java.awt.Color(0, 0, 204));
        lb_6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_7.setBackground(new java.awt.Color(0, 204, 255));
        lb_7.setForeground(new java.awt.Color(0, 0, 204));
        lb_7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_20.setBackground(new java.awt.Color(0, 204, 255));
        lb_20.setForeground(new java.awt.Color(0, 0, 204));
        lb_20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_21.setBackground(new java.awt.Color(0, 204, 255));
        lb_21.setForeground(new java.awt.Color(0, 0, 204));
        lb_21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_8.setBackground(new java.awt.Color(0, 204, 255));
        lb_8.setForeground(new java.awt.Color(0, 0, 204));
        lb_8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_9.setBackground(new java.awt.Color(0, 204, 255));
        lb_9.setForeground(new java.awt.Color(0, 0, 204));
        lb_9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_22.setBackground(new java.awt.Color(0, 204, 255));
        lb_22.setForeground(new java.awt.Color(0, 0, 204));
        lb_22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_23.setBackground(new java.awt.Color(0, 204, 255));
        lb_23.setForeground(new java.awt.Color(0, 0, 204));
        lb_23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_10.setBackground(new java.awt.Color(0, 204, 255));
        lb_10.setForeground(new java.awt.Color(0, 0, 204));
        lb_10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_11.setBackground(new java.awt.Color(0, 204, 255));
        lb_11.setForeground(new java.awt.Color(0, 0, 204));
        lb_11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_24.setBackground(new java.awt.Color(0, 204, 255));
        lb_24.setForeground(new java.awt.Color(0, 0, 204));
        lb_24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_25.setBackground(new java.awt.Color(0, 204, 255));
        lb_25.setForeground(new java.awt.Color(0, 0, 204));
        lb_25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_12.setBackground(new java.awt.Color(0, 204, 255));
        lb_12.setForeground(new java.awt.Color(0, 0, 204));
        lb_12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_26.setBackground(new java.awt.Color(0, 204, 255));
        lb_26.setForeground(new java.awt.Color(0, 0, 204));
        lb_26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_13.setBackground(new java.awt.Color(0, 204, 255));
        lb_13.setForeground(new java.awt.Color(0, 0, 204));
        lb_13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_39.setBackground(new java.awt.Color(0, 204, 255));
        lb_39.setForeground(new java.awt.Color(0, 0, 204));
        lb_39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_38.setBackground(new java.awt.Color(0, 204, 255));
        lb_38.setForeground(new java.awt.Color(0, 0, 204));
        lb_38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_37.setBackground(new java.awt.Color(0, 204, 255));
        lb_37.setForeground(new java.awt.Color(0, 0, 204));
        lb_37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_36.setBackground(new java.awt.Color(0, 204, 255));
        lb_36.setForeground(new java.awt.Color(0, 0, 204));
        lb_36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_35.setBackground(new java.awt.Color(0, 204, 255));
        lb_35.setForeground(new java.awt.Color(0, 0, 204));
        lb_35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_34.setBackground(new java.awt.Color(0, 204, 255));
        lb_34.setForeground(new java.awt.Color(0, 0, 204));
        lb_34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_33.setBackground(new java.awt.Color(0, 204, 255));
        lb_33.setForeground(new java.awt.Color(0, 0, 204));
        lb_33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_46.setBackground(new java.awt.Color(0, 204, 255));
        lb_46.setForeground(new java.awt.Color(0, 0, 204));
        lb_46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_47.setBackground(new java.awt.Color(0, 204, 255));
        lb_47.setForeground(new java.awt.Color(0, 0, 204));
        lb_47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_48.setBackground(new java.awt.Color(0, 204, 255));
        lb_48.setForeground(new java.awt.Color(0, 0, 204));
        lb_48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_49.setBackground(new java.awt.Color(0, 204, 255));
        lb_49.setForeground(new java.awt.Color(0, 0, 204));
        lb_49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_50.setBackground(new java.awt.Color(0, 204, 255));
        lb_50.setForeground(new java.awt.Color(0, 0, 204));
        lb_50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_51.setBackground(new java.awt.Color(0, 204, 255));
        lb_51.setForeground(new java.awt.Color(0, 0, 204));
        lb_51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_52.setBackground(new java.awt.Color(0, 204, 255));
        lb_52.setForeground(new java.awt.Color(0, 0, 204));
        lb_52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_45.setBackground(new java.awt.Color(0, 204, 255));
        lb_45.setForeground(new java.awt.Color(0, 0, 204));
        lb_45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_32.setBackground(new java.awt.Color(0, 204, 255));
        lb_32.setForeground(new java.awt.Color(0, 0, 204));
        lb_32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_31.setBackground(new java.awt.Color(0, 204, 255));
        lb_31.setForeground(new java.awt.Color(0, 0, 204));
        lb_31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_44.setBackground(new java.awt.Color(0, 204, 255));
        lb_44.setForeground(new java.awt.Color(0, 0, 204));
        lb_44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_43.setBackground(new java.awt.Color(0, 204, 255));
        lb_43.setForeground(new java.awt.Color(0, 0, 204));
        lb_43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_30.setBackground(new java.awt.Color(0, 204, 255));
        lb_30.setForeground(new java.awt.Color(0, 0, 204));
        lb_30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_29.setBackground(new java.awt.Color(0, 204, 255));
        lb_29.setForeground(new java.awt.Color(0, 0, 204));
        lb_29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_42.setBackground(new java.awt.Color(0, 204, 255));
        lb_42.setForeground(new java.awt.Color(0, 0, 204));
        lb_42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_41.setBackground(new java.awt.Color(0, 204, 255));
        lb_41.setForeground(new java.awt.Color(0, 0, 204));
        lb_41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_28.setBackground(new java.awt.Color(0, 204, 255));
        lb_28.setForeground(new java.awt.Color(0, 0, 204));
        lb_28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_27.setBackground(new java.awt.Color(0, 204, 255));
        lb_27.setForeground(new java.awt.Color(0, 0, 204));
        lb_27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lb_40.setBackground(new java.awt.Color(0, 204, 255));
        lb_40.setForeground(new java.awt.Color(0, 0, 204));
        lb_40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btn_gen.setText("Gen");
        btn_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genActionPerformed(evt);
            }
        });

        Shuffle.setText("Shuffle");
        Shuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShuffleActionPerformed(evt);
            }
        });

        btn_first.setText("First Card");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_second.setText("Second Card");
        btn_second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secondActionPerformed(evt);
            }
        });

        btn_com.setText("Compare");
        btn_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Shuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_second, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_com, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_34, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(lb_35, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_36, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_37, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lb_38, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_39, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_40, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_41, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lb_42, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(lb_43, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lb_44, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_45, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_46, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_47, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(lb_48, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_49, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_50, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_51, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_52, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Shuffle)
                    .addComponent(btn_gen)
                    .addComponent(btn_first)
                    .addComponent(btn_second)
                    .addComponent(btn_com))
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_13, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(lb_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_26, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(lb_25, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(lb_24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_33, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lb_37, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_38, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_44, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_45, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_49, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lb_50, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                        .addComponent(lb_43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lb_47, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_48, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_51, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_52, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genActionPerformed
        // TODO add your handling code here:
        generate();
    }//GEN-LAST:event_btn_genActionPerformed

    private void ShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShuffleActionPerformed
        // TODO add your handling code here:
        Shuffle(52);
        print();
    }//GEN-LAST:event_ShuffleActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
        One=this.PickRandom();
        
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secondActionPerformed
        // TODO add your handling code here:
        Two=this.PickRandom();
    }//GEN-LAST:event_btn_secondActionPerformed

    private void btn_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comActionPerformed
        // TODO add your handling code here:
        boolean compare=One.Compare(Two);
        String s=null,s2=null;
        if(compare){
        s= One.toString()+" and "+Two.toString()+" are same";
        
        
        }
        else{
        
          s= One.toString()+" and "+Two.toString()+" are not same";
        
        }
        boolean com2=One.isGreater(Two);
        
         if(com2){
        
         s2= One.toString()+" is Greater  Than "+Two.toString();
        
        }
        else{
        s2= One.toString()+" is not  Greater  Than "+Two.toString();
        
        
        }
             JOptionPane.showMessageDialog(this, s, " Comparision ", WIDTH, One.img); 
             JOptionPane.showMessageDialog(this, s2, " Greater Comparision ", WIDTH, Two.img); 
         
    }//GEN-LAST:event_btn_comActionPerformed
 public void print(){
 
     for (int i = 0; i < NCARDS; i++) {
         Front[i].setIcon(card[i].img);
     }
 
 }
 
  public Cards Pick()
      {
   	 if ( currentCard < NCARDS )
   	 { Cards c=card[ currentCard++ ];
             JOptionPane.showMessageDialog(this, " Choosen Card", " Card to be Pick", WIDTH, c.img);
   	    return ( c );
   	 }
   	 else
   	 {
   	    System.out.println("Out of cards error");
   	    return ( null );  // Error;
   	 }
      }

 public Cards PickRandom()
          {
              
              int random=(int)(Math.random()*NCARDS);
   
   	Cards c=card[ random ];
             JOptionPane.showMessageDialog(this, " Choosen Card", " Card to be Pick", WIDTH, c.img);
   	    return ( c );
   	
   	
             }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameofCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameofCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameofCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameofCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameofCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Shuffle;
    private javax.swing.JButton btn_com;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_gen;
    private javax.swing.JButton btn_second;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_10;
    private javax.swing.JLabel lb_11;
    private javax.swing.JLabel lb_12;
    private javax.swing.JLabel lb_13;
    private javax.swing.JLabel lb_14;
    private javax.swing.JLabel lb_15;
    private javax.swing.JLabel lb_16;
    private javax.swing.JLabel lb_17;
    private javax.swing.JLabel lb_18;
    private javax.swing.JLabel lb_19;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_20;
    private javax.swing.JLabel lb_21;
    private javax.swing.JLabel lb_22;
    private javax.swing.JLabel lb_23;
    private javax.swing.JLabel lb_24;
    private javax.swing.JLabel lb_25;
    private javax.swing.JLabel lb_26;
    private javax.swing.JLabel lb_27;
    private javax.swing.JLabel lb_28;
    private javax.swing.JLabel lb_29;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_30;
    private javax.swing.JLabel lb_31;
    private javax.swing.JLabel lb_32;
    private javax.swing.JLabel lb_33;
    private javax.swing.JLabel lb_34;
    private javax.swing.JLabel lb_35;
    private javax.swing.JLabel lb_36;
    private javax.swing.JLabel lb_37;
    private javax.swing.JLabel lb_38;
    private javax.swing.JLabel lb_39;
    private javax.swing.JLabel lb_4;
    private javax.swing.JLabel lb_40;
    private javax.swing.JLabel lb_41;
    private javax.swing.JLabel lb_42;
    private javax.swing.JLabel lb_43;
    private javax.swing.JLabel lb_44;
    private javax.swing.JLabel lb_45;
    private javax.swing.JLabel lb_46;
    private javax.swing.JLabel lb_47;
    private javax.swing.JLabel lb_48;
    private javax.swing.JLabel lb_49;
    private javax.swing.JLabel lb_5;
    private javax.swing.JLabel lb_50;
    private javax.swing.JLabel lb_51;
    private javax.swing.JLabel lb_52;
    private javax.swing.JLabel lb_6;
    private javax.swing.JLabel lb_7;
    private javax.swing.JLabel lb_8;
    private javax.swing.JLabel lb_9;
    // End of variables declaration//GEN-END:variables
}
